"""Strongly typed LangGraph state for the AI Research & Knowledge Agent.

This TypedDict is the single source of truth for what flows through the
LangGraph graph.  Each field has a clear, single responsibility.
"""

from __future__ import annotations

from operator import add
from typing import Annotated, TypedDict

from langchain_core.messages import BaseMessage
from pydantic import BaseModel, Field


# A message is appended via concatenation (LangGraph standard pattern).
Messages = Annotated[list[BaseMessage], add]


class RetrievedDocument(BaseModel):
    """A single document retrieved from the knowledge base."""

    content: str
    source: str = ""
    score: float | None = None


class ToolResult(BaseModel):
    """Result of a single tool invocation."""

    tool_name: str
    result: str
    success: bool = True
    error: str | None = None


class ResearchResult(BaseModel):
    """Summary of a web research task."""

    query: str
    findings: str
    sources: list[str] = Field(default_factory=list)


class AgentState(TypedDict, total=False):
    """Shared state across all graph nodes.

    Fields:
        question:           Original user question.
        answer:             Final answer generated by the agent.
        messages:           Conversation history (LangChain messages).
        retrieved_documents: Documents pulled from the RAG knowledge base.
        tool_results:       Output from executed tools.
        memory_context:     Summary of retrieved short-term + long-term memory.
        user_id:            Stable identifier for the user.
        session_id:         Unique session / thread identifier.
        approval_required:  Whether human approval was requested.
        approved:           Whether the human approved.
        error:              Current error message (null if none).
        retry_count:        How many retry attempts have occurred.
        research_results:   Summaries from web research tasks.
    """

    question: str
    answer: str
    messages: Messages
    retrieved_documents: list[RetrievedDocument]
    tool_results: list[ToolResult]
    memory_context: str
    user_id: str
    session_id: str
    approval_required: bool
    approved: bool
    error: str | None
    retry_count: int
    research_results: list[ResearchResult]
