"""Upload storage, validation and text extraction.

Both the ``/upload`` endpoint and the ``send_email`` tool resolve files through
this module on purpose. An allowlist that exists in two places drifts, and the
one that matters most is the one guarding attachment reads: if ``/upload``
accepted a type that ``send_email`` then refused (or worse, the reverse), the
tool could be talked into reading a path the endpoint never validated.

Files are stored as ``uploads/<user_id>/<file_id><ext>`` with the caller's
original name kept in a ``<file_id>.meta.json`` sidecar. Encoding the id in the
filename means an attachment reference needs no server-side session: the id is
the whole lookup, so a send still resolves after a restart, and a caller cannot
address a file belonging to another user because the id is only ever looked up
inside its own directory.
"""

from __future__ import annotations

import json
import logging
import re
import shutil
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from backend.agent.config import get_settings

logger = logging.getLogger(__name__)


# -------------------------------------------------------------------------
# Limits
# -------------------------------------------------------------------------
#
# Storage limits and the email ceiling are different concerns and live in
# settings so they can be raised without a code change:
#
#   upload_max_file_mb / upload_max_files / upload_max_total_mb  -> storage
#   gmail_max_attachment_mb                                       -> one email
#
# Storage is generous on purpose. Gmail caps a message at 25 MB, so no email
# can carry an arbitrarily large attachment, but there is no reason to refuse
# storing a 200 MB scan — it simply cannot be mailed in one piece.


def _mb(value_mb: int) -> int:
    return int(value_mb) * 1024 * 1024


def max_file_bytes() -> int:
    return _mb(get_settings().upload_max_file_mb)


def max_files_per_request() -> int:
    return int(get_settings().upload_max_files)


def max_total_upload_bytes() -> int:
    return _mb(get_settings().upload_max_total_mb)


def max_total_attachment_bytes() -> int:
    """Ceiling for a single outgoing message."""

    return _mb(get_settings().gmail_max_attachment_mb)


#: How many rows a spreadsheet preview shows before it is truncated.
EXTRACT_ROW_LIMIT = 200

#: Characters of extracted text returned to the client for preview.
EXTRACT_CHAR_LIMIT = 20_000


# -------------------------------------------------------------------------
# Types
# -------------------------------------------------------------------------

#: Always refused, whatever else is allowed. These either execute on the
#: recipient's machine or are the usual first step of an attack chain, and no
#: legitimate reason to mail a file this app produced involves one.
BLOCKED_EXTS = frozenset({".exe", ".bat", ".sh", ".msi", ".js"})

MIME_BY_EXT: dict[str, str] = {
    ".pdf": "application/pdf",
    ".doc": "application/msword",
    ".docx": (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ),
    ".txt": "text/plain",
    ".csv": "text/csv",
    ".xls": "application/vnd.ms-excel",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".pptx": (
        "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    ),
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
}

ALLOWED_EXTS = frozenset(MIME_BY_EXT)

#: Coarse family used by the UI to pick a colour/icon per file.
CATEGORY_BY_EXT: dict[str, str] = {
    ".pdf": "pdf",
    ".doc": "word",
    ".docx": "word",
    ".txt": "text",
    ".csv": "excel",
    ".xls": "excel",
    ".xlsx": "excel",
    ".pptx": "powerpoint",
    ".jpg": "image",
    ".jpeg": "image",
    ".png": "image",
    ".webp": "image",
}

IMAGE_EXTS = frozenset({".jpg", ".jpeg", ".png", ".webp"})

# User ids become a directory name, so they are restricted to characters that
# cannot escape it. Anything else is rejected rather than escaped: a user id is
# generated by this app, and a caller sending "../.." is not one of them.
_SAFE_USER_ID = re.compile(r"^[A-Za-z0-9._-]{1,64}$")

_FILE_ID = re.compile(r"^[0-9a-f]{32}$")


class UploadError(ValueError):
    """A caller-supplied upload was rejected. Safe to show to the user."""


# -------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------


def uploads_root() -> Path:
    """Repository-root ``uploads/``, created on demand."""

    root = Path(__file__).resolve().parents[2] / "uploads"
    root.mkdir(parents=True, exist_ok=True)
    return root


def user_upload_dir(user_id: str) -> Path:
    """Return ``uploads/<user_id>/``, rejecting any id that could escape it."""

    if not _SAFE_USER_ID.match(user_id or ""):
        raise UploadError(
            "Invalid user_id: only letters, digits, dot, dash and underscore "
            "are allowed."
        )

    if user_id in {".", ".."}:
        raise UploadError("Invalid user_id.")

    directory = (uploads_root() / user_id).resolve()

    # Belt and braces: even with the character filter above, confirm the
    # resolved directory is still inside uploads/.
    if uploads_root().resolve() not in directory.parents:
        raise UploadError("Invalid user_id.")

    directory.mkdir(parents=True, exist_ok=True)

    return directory


def extension_of(filename: str) -> str:
    return Path(filename or "").suffix.lower()


def validate_extension(filename: str) -> str:
    """Return the validated extension, or raise :class:`UploadError`."""

    ext = extension_of(filename)

    if not ext:
        raise UploadError(f"'{filename}' has no file extension.")

    # Checked before the allowlist so a blocked type is reported as blocked
    # rather than as a generic unsupported type.
    if ext in BLOCKED_EXTS:
        raise UploadError(
            f"'{ext}' files are never accepted ({filename})."
        )

    if ext not in ALLOWED_EXTS:
        allowed = ", ".join(sorted(ALLOWED_EXTS))
        raise UploadError(
            f"'{ext}' is not an allowed upload type. Allowed: {allowed}."
        )

    return ext


# -------------------------------------------------------------------------
# Text extraction
# -------------------------------------------------------------------------


def _extract_pdf(path: Path) -> str:
    from pypdf import PdfReader

    reader = PdfReader(str(path))
    pages = []

    for number, page in enumerate(reader.pages, start=1):
        text = page.extract_text() or ""
        pages.append(f"--- page {number} ---\n{text.strip()}")

    return "\n\n".join(pages)


def _extract_docx(path: Path) -> str:
    import docx

    document = docx.Document(str(path))
    parts = [p.text for p in document.paragraphs if p.text and p.text.strip()]

    for table in document.tables:
        for row in table.rows:
            cells = [c.text.strip() for c in row.cells]
            if any(cells):
                parts.append(" | ".join(cells))

    return "\n".join(parts)


def _extract_txt(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _extract_tabular(path: Path, ext: str) -> str:
    import pandas as pd

    if ext == ".csv":
        frame = pd.read_csv(str(path))
    elif ext == ".xlsx":
        frame = pd.read_excel(str(path), engine="openpyxl")
    else:  # .xls, via xlrd
        frame = pd.read_excel(str(path), engine="xlrd")

    truncated = len(frame) > EXTRACT_ROW_LIMIT
    view = frame.head(EXTRACT_ROW_LIMIT)

    text = view.to_string()

    if truncated:
        text += (
            f"\n\n[showing first {EXTRACT_ROW_LIMIT} of {len(frame)} rows]"
        )

    return text


def _extract_pptx(path: Path) -> str:
    from pptx import Presentation

    presentation = Presentation(str(path))
    slides = []

    for number, slide in enumerate(presentation.slides, start=1):
        chunks = []

        for shape in slide.shapes:
            if shape.has_text_frame:
                text = shape.text_frame.text.strip()
                if text:
                    chunks.append(text)

        if chunks:
            slides.append(f"--- slide {number} ---\n" + "\n".join(chunks))

    return "\n\n".join(slides)


def make_thumbnail(path: Path, file_id: str, user_id: str) -> str | None:
    """Write a small preview JPEG for an image upload.

    Returns the thumbnail's relative filename, or None when the image could not
    be decoded. A corrupt or non-image payload is reported rather than
    described: the alternative is inventing a description of a picture nobody
    looked at.
    """

    try:
        from PIL import Image
    except ImportError:  # pragma: no cover - Pillow is a hard requirement
        logger.warning("Pillow unavailable; skipping thumbnail")
        return None

    target_dir = user_upload_dir(user_id) / "thumbnails"
    target_dir.mkdir(parents=True, exist_ok=True)
    name = f"{file_id}.jpg"

    try:
        with Image.open(path) as image:
            image.thumbnail((320, 320))

            if image.mode not in ("RGB", "L"):
                # PNG transparency and palette modes have no direct JPEG
                # equivalent; flatten onto white rather than failing.
                image = image.convert("RGBA")
                flat = Image.new("RGB", image.size, (255, 255, 255))
                flat.paste(image, mask=image.split()[3])
                image = flat
            elif image.mode == "L":
                image = image.convert("RGB")

            image.save(target_dir / name, format="JPEG", quality=80)

        return f"thumbnails/{name}"

    except Exception as exc:  # noqa: BLE001 - any decode failure is non-fatal
        logger.warning("Thumbnail failed for %s: %s", path.name, exc)
        return None


def extract_text(path: Path, ext: str) -> tuple[str, str | None]:
    """Return ``(text, thumbnail_name)`` for an upload.

    Extraction failures are reported in the returned text rather than raised.
    A file that cannot be parsed is still perfectly sendable — refusing the
    upload because a PDF happens to be image-only would be worse than sending
    it without a text preview.
    """

    thumbnail: str | None = None

    try:
        if ext == ".pdf":
            return _extract_pdf(path), None
        if ext == ".docx":
            return _extract_docx(path), None
        if ext == ".txt":
            return _extract_txt(path), None
        if ext in {".csv", ".xls", ".xlsx"}:
            return _extract_tabular(path, ext), None
        if ext == ".pptx":
            return _extract_pptx(path), None

        if ext in IMAGE_EXTS:
            thumbnail = make_thumbnail(path, path.stem, _owner_of(path))
            # Deliberately no description. There is no vision model wired into
            # this path, and a caption invented from a filename would be a lie
            # the user could act on.
            return "Image ready to send. No text preview available.", thumbnail

        if ext == ".doc":
            return (
                "Legacy .doc file attached as-is. Text extraction is not "
                "supported for the old binary Word format; save it as .docx "
                "to get a preview.",
                None,
            )

    except Exception as exc:  # noqa: BLE001
        logger.warning("Text extraction failed for %s: %s", path.name, exc)
        return f"Attached as-is. Text could not be extracted ({exc}).", None

    return "Attached as-is.", None


# -------------------------------------------------------------------------
# Storage
# -------------------------------------------------------------------------


@dataclass
class StoredFile:
    file_id: str
    original_name: str
    stored_name: str
    ext: str
    mime: str
    category: str
    size: int
    path: Path
    text: str = ""
    thumbnail: str | None = None
    meta: dict[str, Any] = field(default_factory=dict)

    def public(self) -> dict[str, Any]:
        return {
            "file_id": self.file_id,
            "name": self.original_name,
            "ext": self.ext,
            "mime": self.mime,
            "category": self.category,
            "size": self.size,
            "text_preview": self.text[:EXTRACT_CHAR_LIMIT],
            "thumbnail": self.thumbnail,
        }


_OWNERS: dict[str, str] = {}


def _owner_of(path: Path) -> str:
    return _OWNERS.get(path.stem, "default_user")


def store_upload(
    filename: str,
    source: Any,
    user_id: str,
) -> StoredFile:
    """Validate and persist one upload.

    ``source`` is anything with ``read()`` (a Starlette ``UploadFile`` works),
    which keeps this testable without constructing a request.
    """

    ext = validate_extension(filename)

    directory = user_upload_dir(user_id)

    file_id = uuid.uuid4().hex
    stored_name = f"{file_id}{ext}"
    destination = directory / stored_name

    written = 0
    cap = max_file_bytes()

    try:
        with destination.open("wb") as handle:
            while True:
                chunk = source.read(1024 * 256)

                if not chunk:
                    break

                written += len(chunk)

                # Enforced while streaming, not after: a 5 GB upload must be cut
                # off at the cap, not buffered first and measured afterwards.
                if written > cap:
                    raise UploadError(
                        f"'{filename}' exceeds the {cap // (1024 * 1024)} MB "
                        "per-file limit (upload_max_file_mb)."
                    )

                handle.write(chunk)

    except Exception:
        destination.unlink(missing_ok=True)
        raise

    if written == 0:
        destination.unlink(missing_ok=True)
        raise UploadError(f"'{filename}' is empty.")

    _OWNERS[file_id] = user_id

    text, thumbnail = extract_text(destination, ext)

    record = StoredFile(
        file_id=file_id,
        original_name=Path(filename).name[:255],
        stored_name=stored_name,
        ext=ext,
        mime=MIME_BY_EXT[ext],
        category=CATEGORY_BY_EXT[ext],
        size=written,
        path=destination,
        text=text,
        thumbnail=thumbnail,
    )

    (directory / f"{file_id}.meta.json").write_text(
        json.dumps(
            {
                "original_name": record.original_name,
                "ext": ext,
                "size": written,
                "uploaded_at": datetime.now(timezone.utc).isoformat(),
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    logger.info(
        "Stored upload %s (%s, %d bytes) for user %s",
        record.original_name, ext, written, user_id,
    )

    return record


def store_uploads(
    files: list[tuple[str, Any]],
    user_id: str,
) -> list[StoredFile]:
    """Persist a batch, enforcing the per-request count and size caps."""

    if not files:
        raise UploadError("No files were uploaded.")

    max_files = max_files_per_request()
    total_cap = max_total_upload_bytes()

    if len(files) > max_files:
        raise UploadError(
            f"At most {max_files} files per upload "
            f"(received {len(files)})."
        )

    _check_free_space()

    stored: list[StoredFile] = []
    total = 0

    try:
        for filename, source in files:
            record = store_upload(filename, source, user_id)
            total += record.size

            if total > total_cap:
                raise UploadError(
                    "Combined upload size exceeds the "
                    f"{total_cap // (1024 * 1024)} MB limit "
                    "(upload_max_total_mb)."
                )

            stored.append(record)

    except Exception:
        # All-or-nothing: leaving half a batch on disk would let a rejected
        # upload still be referenced by id afterwards.
        for record in stored:
            _delete_stored(record)
        raise

    return stored


def _delete_stored(record: StoredFile) -> None:
    record.path.unlink(missing_ok=True)

    meta = record.path.parent / f"{record.file_id}.meta.json"
    meta.unlink(missing_ok=True)

    thumbnail = record.path.parent / "thumbnails" / f"{record.file_id}.jpg"
    thumbnail.unlink(missing_ok=True)

    _OWNERS.pop(record.file_id, None)


# -------------------------------------------------------------------------
# Resolution for sending
# -------------------------------------------------------------------------


def resolve_attachments(
    user_id: str,
    file_ids: list[str],
) -> list[StoredFile]:
    """Resolve attachment ids to files inside this user's upload directory.

    Raises :class:`UploadError` for anything that is not a readable, allowed
    file already present in ``uploads/<user_id>/``.
    """

    if not file_ids:
        return []

    total_cap = max_total_attachment_bytes()

    directory = user_upload_dir(user_id)
    resolved: list[StoredFile] = []
    total = 0

    for file_id in file_ids:
        candidate = str(file_id or "").strip()

        if not _FILE_ID.match(candidate):
            raise UploadError(f"Invalid attachment id: {candidate!r}")

        matches = sorted(directory.glob(f"{candidate}.*"))

        # The sidecar shares the id, so drop it before looking for the payload.
        payload = [p for p in matches if not p.name.endswith(".meta.json")]

        if len(payload) != 1:
            raise UploadError(
                f"Attachment {candidate} was not found for this user."
            )

        path = payload[0]

        # The glob is built from a validated hex id and a fixed directory, so
        # this cannot escape — but the resolved path is checked anyway, because
        # this function reads a caller-supplied id.
        if path.resolve().parent != directory.resolve():
            raise UploadError(f"Attachment {candidate} is outside your uploads.")

        ext = extension_of(path.name)
        validate_extension(path.name)

        size = path.stat().st_size
        total += size

        if total > total_cap:
            raise UploadError(
                f"Attachments total {total / (1024 * 1024):.0f} MB, over the "
                f"{total_cap // (1024 * 1024)} MB that fits in one email. "
                "Gmail refuses messages above 25 MB, so send fewer files or "
                "raise gmail_max_attachment_mb (gmail will still cap it at "
                "25 MB)."
            )

        original_name = path.stem

        meta_path = directory / f"{candidate}.meta.json"
        if meta_path.exists():
            try:
                meta = json.loads(meta_path.read_text(encoding="utf-8"))
                original_name = meta.get("original_name") or original_name
            except (json.JSONDecodeError, OSError):
                logger.warning("Unreadable sidecar for %s", candidate)

        resolved.append(
            StoredFile(
                file_id=candidate,
                original_name=original_name,
                stored_name=path.name,
                ext=ext,
                mime=MIME_BY_EXT[ext],
                category=CATEGORY_BY_EXT[ext],
                size=size,
                path=path,
                # Recomputed rather than read from the sidecar: the thumbnail is
                # derivable from the id alone, and this path is reached on every
                # send as well as on preview requests.
                thumbnail=(
                    f"thumbnails/{candidate}.jpg"
                    if (directory / "thumbnails" / f"{candidate}.jpg").exists()
                    else None
                ),
            )
        )

    return resolved


def clear_user_uploads(user_id: str) -> None:
    """Remove everything belonging to one user. Used by tests."""

    shutil.rmtree(user_upload_dir(user_id), ignore_errors=True)


def _check_free_space() -> None:
    """Refuse new uploads when the disk is nearly full.

    The per-file cap alone still permits filling a volume, and a disk-full error
    part-way through a write leaves a truncated file that looks valid. Checking
    first turns that into an explanation.
    """

    required = _mb(get_settings().upload_min_free_mb)

    try:
        free = shutil.disk_usage(uploads_root()).free
    except OSError as exc:  # pragma: no cover - unusual filesystem failure
        logger.warning("Could not check free space: %s", exc)
        return

    if free < required:
        raise UploadError(
            f"Only {free / (1024 * 1024):.0f} MB free on disk; uploads need "
            f"{required // (1024 * 1024)} MB to spare. Free some space first."
        )


# -------------------------------------------------------------------------
# Async entry point
# -------------------------------------------------------------------------

#: Bytes buffered in memory before an upload spills to a temporary file.
SPOOL_MEMORY_LIMIT = 2 * 1024 * 1024


async def store_uploads_async(
    items: list[tuple[str, Any]],
    user_id: str,
) -> list[StoredFile]:
    """Spool async upload sources to disk, then store them.

    Starlette's ``UploadFile.read`` is a coroutine, so it cannot be handed to
    the synchronous writer. Each file is drained into a spooled temporary file
    first, with the per-file cap enforced *during* the drain — reading the whole
    body into memory and measuring afterwards would let a caller send a 2 GB
    request to be rejected only once it had already been buffered.
    """

    import tempfile

    if not items:
        raise UploadError("No files were uploaded.")

    max_files = max_files_per_request()
    cap = max_file_bytes()

    if len(items) > max_files:
        raise UploadError(
            f"At most {max_files} files per upload "
            f"(received {len(items)})."
        )

    _check_free_space()

    spooled: list[tuple[str, Any]] = []

    try:
        for filename, source in items:
            handle = tempfile.SpooledTemporaryFile(
                max_size=SPOOL_MEMORY_LIMIT, mode="w+b"
            )
            total = 0

            try:
                while True:
                    chunk = await source.read(256 * 1024)

                    if not chunk:
                        break

                    total += len(chunk)

                    if total > cap:
                        raise UploadError(
                            f"'{filename}' exceeds the "
                            f"{cap // (1024 * 1024)} MB per-file limit "
                            "(upload_max_file_mb)."
                        )

                    handle.write(chunk)

                handle.seek(0)

            except Exception:
                handle.close()
                raise

            spooled.append((filename, handle))

        return store_uploads(spooled, user_id)

    finally:
        for _, handle in spooled:
            try:
                handle.close()
            except Exception:  # noqa: BLE001
                pass